# Site settings
title: Samtools organisation
description: "Samtools organisation for next-generation sequencing developers: htslib C&nbsp;API, htsjdk Java API, file format specifications, and samtools/bcftools source code."
baseurl: ""
url: "http://samtools.github.io"
github_username: samtools

# Build settings
markdown: kramdown
permalink: pretty
